#!/usr/bin/env python
# -*- coding: utf-8 -*-


from os.path import split
import argparse
import pandas as pd

# Import from mlproject
import mlproject
from mlproject.distance import haversine

if __name__ == '__main__':
    description = 'stkrgcp_description'
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument(
        '--coords',
        nargs = '+',
        help='get coordinates to calculat distance',
        )

    args = parser.parse_args()

    lon1, lat1, lon2, lat2 = args.coords

    dist = haversine(float(lon1), float(lat1), float(lon2), float(lat2))
    print(dist)